name: CD Yandex
on:
    workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build docker image
              run: docker build . --file Dockerfile --tag cr.yandex/${{secrets.YC_REGISTRY_ID }}/getmovie:latest
            - name: Login to YC Registry
              uses: docker/login-action@v3.0.0
              with:
                registry: cr.yandex
                username: json_key
                password: ${{ secrets.YC_KEYS }}
            - name: Push tag to YC Registry
              run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/getmovie:latest 
